addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.12.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-bloop"           % "1.5.17")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.14")
addSbtPlugin("org.http4s"        % "sbt-http4s-org"      % "0.16.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
// addSbtPlugin("com.github.sbt"    % "sbt-github-actions"  % "0.15.0")
// addSbtPlugin("org.typelevel"     % "sbt-typelevel"       % "0.4.19")
