addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.4")
addSbtPlugin("org.http4s"        % "sbt-http4s-org"      % "0.14.12")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.9.0")
// addSbtPlugin("org.typelevel"     % "sbt-typelevel"       % "0.4.19")
